# .platform.app.yaml

# The name of this application, which must be unique within a project.
build:
    flavor: composer

# The size of the persistent disk of the application (in MB).
disk: 2048

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
    '/temp': 'shared:files/temp'
    '/log': 'shared:files/log'

# The configuration of app when it is exposed to the web.
name: 'app'

# The type key specifies the language and version for your application.
type: 'php:7.0'

# On PHP, there are multiple build flavors available.
web:
    # Specific parameters for different URL prefixes.
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'www'
            # The front-controller script which determines where to send
            # non-static requests.
            passthru: '/index.php'
            # How long to allow static assets from this location to be cached.
            expires: 5m
            # Deny access to static files in this location.
            allow: false
            # Rules for specific URI patterns.
            rules:
                # Allow access to common static files.
                '\.(pdf|js|ico|gif|jpg|png|css|rar|zip|tar\.gz|map)$'
                    allow: true
                '^/robots\.txt$':
                    allow: true